apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    username: foben
spec:
  containers:
    - name: main
      image: gitopsworkshop/my-app:v1
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: foben-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    myapp: foben
spec:
  ports:
  - name: dummy
    port: 8080
  selector:
    username: foben
