apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    FOBEN_SECRET: AgClT49c8581RZ5AEOLS9E0vNAqpXvczWllZPh3K8zvjd1uPMAhAhMsh78r+Jr5g+5b55lEJoPhtX1H5Giq3a6htrE/kCWfbVKHgD+TVmTj+bbb8uZIPNwF1CZMiNxb3FMHy5VbbTHUaMY6g8aZLyKUTv2UiznS9BfhMSJwbhixYAUR8ZRsU/VeSoXLi6H/iGRa3gwuXwrK8HGg7sU+Ds+FzjMIGkgM88nIo03NuNZUCJsGct4t5lkaIFpY67YWevVMk2o367fyClk1xSArE8N4zR9dYbPkt7iImfaD9b3A/8O83tvs4BnsMAxWzSWvy1u4nyq2YrqBAQ0plqcPdzGLOMF2OLdWvdYFrB3ZFxVL0zbZoEhqunx5Etvs2EJNgc0/wur45HCZ2Uhm4Vx0ds+sJYyB3RagD5BYTqwUr+kiZInEo89Bu0UnRgdNw3SzjimItzRppt74LSXOlx83IdOSZh/XTmSFin4JPiZL4+jxxEB2QCUaVOx1+RGTE1hjWy+epdEOh1k8JtIwxIzzYCyGUJkXmkgNGGA5hU5MNQPjLsunbX4V3svhQIY4PUt4oKJbZ4I2mIyaIxgeuWSOUNsdKNIypgHbaZ24K5gLpmm/ReanC3NBLNMrgRA2+Fpw5odLGEYsX4X6m6imSB+pps5wd8/BQx3hidmO7uEniw9iKwhW/9VEtLEvMyVPWga9sIFQsJamIX6Q=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
status: {}

